spring:
  application:
    name: urban_mineral
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:pro}



server:
  port: 8081
  servlet:
    context-path: /urban_mineral



lombok:
  equalsAndHashCode:
    callSuper: call


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.um.domain.po


mapper:
  mappers: com.um.common.MyMapper
  not-empty: false
  identity: MYSQL


#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql




sms:
  signName: 安行优客
  templateCode: SMS_151690249
  templateParam: "{\"code\":\"%s\"}"